//
//  Questions.swift
//  Paranoia
//
//  Created by Emily Mearns on 5/24/18.
//  Copyright © 2018 em. All rights reserved.
//

import Foundation

struct Questions {
    
    let all: [String] = [
        "Who is most likely to be a serial killer?",
        "Which two people would most likely rob a bank together?",
        "Who would be the most paranoid right now if you were to look at them and say their name out loud?",
        "Who would be most likely to win a Nobel prize?",
        "Who is most likely to make you cry for any reason?",
        "Who is the worst at flipping a coin?",
        "Who gets embarrassed the easiest?",
        "Who would is the most likely to eat food off the floor?",
        "Who would make the best parent?",
        "Who is most likely to have bullied you in grade school?",
        "Who is most likely to start laughing at a funeral?",
        "Who is most likely to become President of the United States?",
        "Who is most likely to star in a sitcom, only to have it canceled after one season?",
        "Who has the nicest smile?",
        "Who has the nicest hair?",
        "Who do you think smells the nicest?",
        "Who has more friends than anyone else in the circle?",
        "Who has the funnest parents?",
        "Who is most likely to become famous?",
        "Who do you think has the worst breath right now based on what they’ve eaten today?",
        "Who is the most gullible person here?",
        "Which two people would most likely be voted Prom King and Queen?",
        "Who is most likely to run out on their wedding day?",
        "Who has the shortest temper in the circle?",
        "Who is most likely to get banned from Disneyland?",
        "Who is most likely to plan a mass zoo breakout?",
        "Who is most likely to follow the latest diet trend?",
        "Who had the best ‘glow up’ over the years?",
        "Who keeps themselves in the best shape?",
        "Who is most likely to dream in cartoon form?",
        "Who has the most maniacal/evil laugh?",
        "Who is most likely to show up at your birthday party without a gift?",
        "Who is most likely to actually be an alien right now?",
        "Who is most likely to be a spy?",
        "Who is most likely to be hiding their true identity?",
        "Who is least likely to have showered today?",
        "Who is most likely to be on a reality TV show?",
        "Who is most likely to join the circus at some point in their life?",
        "Who is most likely to quit their job and travel the world?",
        "Whose foot would you least likely want to lick?",
        "Who is the biggest romantic in the group?",
        "Who would most likely throw up if they ate a bug?",
        "Who is the least likely to go skydiving?",
        "Who is the most attractive person but doesn’t realize it?",
        "Who was the biggest cheater in school?",
        "Who would most likely get arrested for celebrity stalking?",
        "Who is mostly likely to get caught in a pyramid scheme?",
        "Which two people are most likely to break out in a fist fight right now?",
        "Who hates people the most?",
        "If you had to be surgically attached to one person for the rest of your life, who would it be?",
        "Which two people are most and least likely to survive a zombie apocalypse?",
        "Who would most likely have a foot fetish?",
        "Who would be the ugly twin, if they had a twin?",
        "If you had to be stuck on a desert island with two other people, who would they be?",
        "Who is the person in the circle who is least like you?",
        "Who would make the best shock jock radio host?",
        "Who in the circle is most likely to elope in Vegas, only to get it annulled 3 months later?",
        "Who is most likely to come back from the pet store with a weird exotic pet?",
        "Who is most likely to fake sick to get out of a bad date?",
        "Who is the least athletic person in the room?",
        "Who could you see one day becoming a B-list celebrity?",
        "Who would make the worst therapist?",
        "Who is the funniest person in the room?",
        "Who is always in a good mood?",
        "Who is most likely to win an Oscar?",
        "Who has the best shaped head?",
        "Who is the best singer?",
        "Who is most likely to be a crazy cat lady?",
        "Who has the coolest face in the room?",
        "Who is rocking a unibrow?",
        "Who is the biggest drama queen?",
        "Who would make the best President of the U.S.?",
        "Who is most likely to find an island and start their own country?",
        "Who would most likely start a mutiny on a ship?",
        "Who looks the most like they just rolled out of bed?",
        "Who is the least likely to know the words to the Star Spangled Banner?",
        "Who is most likely to live in a nudist colony?",
        "Who is the best dancer?",
        "Whose hands are probably the sweatiest right now?",
        "Who would most likely be taken down in a scandal?",
        "If you needed someone to bail you out of jail, who would you call?",
        "Who is most likely to have candy on their person right now?",
        "Who is most likely to be at church on a Sunday?",
        "Whose life is most like a romantic comedy?",
        "Who dresses up the best?",
        "Who is most likely to tag you in a meme?",
        "Who is the pickiest eater?",
        "Who would win in a pizza eating contest?",
        "Who is most likely to make fart sounds with their mouths and think its funny?",
        "Who in the circle do you think will retire first?",
        "Who would you be least surprised to find on a park bench feeding pigeons?",
        "Who do you think got the highest SAT score?",
        "If you had to hire someone to cook for you for the rest of your life, who would it be?",
        "Who is most likely to get caught picking their scabs?",
        "Who most needs a haircut right now?",
        "Who is most likely to start a heated political discussion tonight?",
        "Who avoids confrontation like the plague?",
        "Who has the biggest heart?",
        "Who would most likely randomly come home with puppy?",
        "Who is most likely to die in a corn maze?",
        "Who would most likely try to baptize you without you knowing?",
        "If you had to marry the sibling of someone in the circle, who would it be?",
        "Who can pull off hats the best?",
        "Who is the ugliest crier?",
        "Who has the cutest sneeze?",
        "Who has the sexiest name in the circle? Who has the least sexy?",
        "Who most likely got picked last in kickball on the playground?",
        "Who is most likely to dine and dash?",
        "Who is most likely to end up in a pyramid scheme?",
        "Who was the most recent person to have clogged a toilet?",
        "Who is most likely to start a kitchen fire while cooking?",
        "If you had to lick someone’s feet in the circle, who would it be?",
        "Who is most likely to start and end a diet within the same day?",
        "Who is most likely to get killed while trying to cow tip?",
        "Who is most likely to have a burrito in their bag right now?",
        "Who would most likely adopt a dog, only to return it a week later?",
        "Who is going to be the strictest parent?",
        "Who is most likely to throw someone else in a dumpster if they went to high school together?",
        "Who is most likely to not shower for a week?",
        "Who is most likely to have FBI agents arrive at their door?",
        "Who do you think would eat a dog in time of need?",
        "Who here would you choose as your zombie apocalypse survival buddy?",
        "Which two people here would have the cutest babies?",
        "Which person here is most likely to have a Dwayne The Rock Johnson tattoo?",
        "Who here is most likely to be famous someday?",
        "Which person here could actually survive in the wilderness for a month?",
        "If this were Survivor, who would you vote out first?",
        "If this room suddenly caught on fire and you could only save one person, who would you pick?",
        "Who here has the weirdest laugh?",
        "Who here do you think cries the most?",
        "If you could offer one person in this room an opportunity to hug Oprah, who would you pick?",
        "Who would win a spontaneous dance-off?",
        "Who is most likely to buy expensive clothes with money they don’t have?",
        "Who in the circle has the most money?",
        "Who in the circle has the highest IQ?",
        "Who is most likely to sleep with their boss to advance their career?",
        "Who is most likely to get fired from their job?",
        "Who is most likely to quit playing this game right now?",
        "Who in the circle is most likely to fall asleep right now?",
        "Who in the circle would be most likely to pee their pants?",
        "Who is the most attractive?",
        "Who smells the worst?",
        "Who is the smartest?",
        "Who would you most like to be stuck on a desert island with?",
        "Who has pooped the most recently?",
        "Who is the best at their job?",
        "Who would you be least likely to let babysit your children?",
        "Who would be the last person alive in a zombie apocalypse?",
        "Who would you trust the most to keep a really juicy secret?",
        "Who has the best hair?",
        "Who could use a makeover the most?",
        "Who would you want to trade lives with for a day?",
        "Who is the most likely to become famous?",
        "Who here is most likely to end up in prison?",
        "Who are you most likely to date?",
        "Who in the circle are you most attracted to?",
        "Who in the circle do you like the most?",
        "Who in the circle do you like the least?",
        "Who in the circle is most likely to cheat on their significant other?",
        "Who in the circle is most likely to steal?",
        "Who in the circle is the least friendly?",
        "Who in the circle is the most friendly?",
        "Who in the circle is most likely to have a weird fetish",
        "Who in the circle is the nicest?",
        "Who in the circle is the meanest?",
        "Who in the circle is the most blunt?",
        "Who in the circle do you want to date?",
        "Who in the circle do you want to be best friends with?",
        "Who in the circle likes you the least?",
        "Who would you feel the most uncomfortable being forced to have a one-on-one conversation with?",
        "If you could eliminate one person from the group, who would you choose?",
        "Who in the group do you think is the most like you?",
        "Who would you want to travel with?",
        "Who do you admire most in the group?",
        "Who are you least likely to strike up a conversation with?",
        "Who in the group do you think are frenemies?",
        "Who would be the best lover?",
        "Who is most likely to steal your Easter eggs?",
        "Who probably has the stinkiest socks?",
        "Which two people are most likely to hook up?",
        "Who is the most attractive in the circle?",
        "Which two people would make the cutest babies?",
        "Who would you have had a playground crush on in elementary school?",
        "Which three people would most likely be in a love triangle?",
        "If you had to cover someone in peanut butter and lick it off, who would it be?",
        "Which two people are most likely to start a meth lab together?",
        "Who is most likely to join a cult?",
        "Who is most likely to start a cult?",
        "Who is likely the best kisser in the circle?",
        "Who is likely the worst kisser in the circle?",
        "Who is most likely to get a restraining order against them?",
        "Who is most likely to be convicted of a felony?",
        "Who do you think has kissed the most people?",
        "Who has kissed the least number of people?",
        "Who do you think has peed themselves the most times?",
        "Who in the circle would your parents most likely hate the most?",
        "Who is most likely to be hiding a hickey right now?",
        "Who is most likely to be able to tie a cherry stem in a knot with their tongue?",
        "Who is most likely to marry for money?",
        "Who would most likely sell one of their (disposable) organs on the black market for extra cash?",
        "Who is most likely to take off their clothes and start streaking right now?",
        "Who would die from something stupid?",
        "Who is most likely to be high right now?",
        "Who is most likely to be secretly dating someone right now?",
        "Who is most likely to live in a nudist colony?",
        "Who would you most suspect would spit in your food?",
        "Who will make the hottest mom or dad?",
        "Whose body would you be most willing to eat sushi off of?",
        "Which person would you most likely bring home to your parents on Thanksgiving and lie that they are your significant other?",
        ]
}
